name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  formz: ^0.6.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mobile_scanner: ^3.5.2
  path_provider: ^2.1.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.2
  rxdart: ^0.27.7
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: L10n
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
