class Visitor {
  final String id;
  final String name;

  Visitor({
    required this.id,
    required this.name,
  });

  static List<Visitor> mock = [
    Visitor(id: "1", name: "Василий Пупкин"),
    Visitor(id: "1", name: "Масленникова Ева"),
    Visitor(id: "1", name: "Шаповалов Иван"),
    Visitor(id: "1", name: "Мартынова Мария"),
    Visitor(id: "1", name: "Иванова Элина"),
    Visitor(id: "1", name: "Романова Анна"),
    Visitor(id: "1", name: "Николаев Руслан"),
    Visitor(id: "1", name: "Винокурова Мария"),
    Visitor(id: "1", name: "Кириллов Никита"),
    Visitor(id: "1", name: "Белоусов Фёдор"),
    Visitor(id: "1", name: "Суворова Арина"),
    Visitor(id: "1", name: "Осипова Ева"),
    Visitor(id: "1", name: "Князев Фёдор"),
    Visitor(id: "1", name: "Маслова Лейла"),
    Visitor(id: "1", name: "Малышев Мирослав"),
    Visitor(id: "1", name: "Морозов Данила"),
    Visitor(id: "1", name: "Серебрякова Анастасия"),
    Visitor(id: "1", name: "Федоров Александр"),
    Visitor(id: "1", name: "Василий Пупкин"),
    Visitor(id: "1", name: "Масленникова Ева"),
    Visitor(id: "1", name: "Шаповалов Иван"),
    Visitor(id: "1", name: "Мартынова Мария"),
    Visitor(id: "1", name: "Иванова Элина"),
    Visitor(id: "1", name: "Романова Анна"),
    Visitor(id: "1", name: "Николаев Руслан"),
    Visitor(id: "1", name: "Винокурова Мария"),
    Visitor(id: "1", name: "Кириллов Никита"),
    Visitor(id: "1", name: "Белоусов Фёдор"),
    Visitor(id: "1", name: "Суворова Арина"),
    Visitor(id: "1", name: "Осипова Ева"),
    Visitor(id: "1", name: "Князев Фёдор"),
    Visitor(id: "1", name: "Маслова Лейла"),
    Visitor(id: "1", name: "Малышев Мирослав"),
    Visitor(id: "1", name: "Морозов Данила"),
    Visitor(id: "1", name: "Серебрякова Анастасия"),
    Visitor(id: "1", name: "Федоров Александр"),
    Visitor(id: "1", name: "Василий Пупкин"),
    Visitor(id: "1", name: "Масленникова Ева"),
    Visitor(id: "1", name: "Шаповалов Иван"),
    Visitor(id: "1", name: "Мартынова Мария"),
    Visitor(id: "1", name: "Иванова Элина"),
    Visitor(id: "1", name: "Романова Анна"),
    Visitor(id: "1", name: "Николаев Руслан"),
    Visitor(id: "1", name: "Винокурова Мария"),
    Visitor(id: "1", name: "Кириллов Никита"),
    Visitor(id: "1", name: "Белоусов Фёдор"),
    Visitor(id: "1", name: "Суворова Арина"),
    Visitor(id: "1", name: "Осипова Ева"),
    Visitor(id: "1", name: "Князев Фёдор"),
    Visitor(id: "1", name: "Маслова Лейла"),
    Visitor(id: "1", name: "Малышев Мирослав"),
    Visitor(id: "1", name: "Морозов Данила"),
    Visitor(id: "1", name: "Серебрякова Анастасия"),
    Visitor(id: "1", name: "Федоров Александр"),
    Visitor(id: "1", name: "Василий Пупкин"),
    Visitor(id: "1", name: "Масленникова Ева"),
    Visitor(id: "1", name: "Шаповалов Иван"),
    Visitor(id: "1", name: "Мартынова Мария"),
    Visitor(id: "1", name: "Иванова Элина"),
    Visitor(id: "1", name: "Романова Анна"),
    Visitor(id: "1", name: "Николаев Руслан"),
    Visitor(id: "1", name: "Винокурова Мария"),
    Visitor(id: "1", name: "Кириллов Никита"),
    Visitor(id: "1", name: "Белоусов Фёдор"),
    Visitor(id: "1", name: "Суворова Арина"),
    Visitor(id: "1", name: "Осипова Ева"),
    Visitor(id: "1", name: "Князев Фёдор"),
    Visitor(id: "1", name: "Маслова Лейла"),
    Visitor(id: "1", name: "Малышев Мирослав"),
    Visitor(id: "1", name: "Морозов Данила"),
    Visitor(id: "1", name: "Серебрякова Анастасия"),
    Visitor(id: "1", name: "Федоров Александр"),
  ];
}
