class Visitor {
  final String name;

  Visitor({
    required this.name,
  });

  static List<Visitor> mock = [
    Visitor(name: "Василий Пупкин"),
    Visitor(name: "Масленникова Ева"),
    Visitor(name: "Шаповалов Иван"),
    Visitor(name: "Мартынова Мария"),
    Visitor(name: "Иванова Элина"),
    Visitor(name: "Романова Анна"),
    Visitor(name: "Николаев Руслан"),
    Visitor(name: "Винокурова Мария"),
    Visitor(name: "Кириллов Никита"),
    Visitor(name: "Белоусов Фёдор"),
    Visitor(name: "Суворова Арина"),
    Visitor(name: "Осипова Ева"),
    Visitor(name: "Князев Фёдор"),
    Visitor(name: "Маслова Лейла"),
    Visitor(name: "Малышев Мирослав"),
    Visitor(name: "Морозов Данила"),
    Visitor(name: "Серебрякова Анастасия"),
    Visitor(name: "Федоров Александр"),
    Visitor(name: "Василий Пупкин"),
    Visitor(name: "Масленникова Ева"),
    Visitor(name: "Шаповалов Иван"),
    Visitor(name: "Мартынова Мария"),
    Visitor(name: "Иванова Элина"),
    Visitor(name: "Романова Анна"),
    Visitor(name: "Николаев Руслан"),
    Visitor(name: "Винокурова Мария"),
    Visitor(name: "Кириллов Никита"),
    Visitor(name: "Белоусов Фёдор"),
    Visitor(name: "Суворова Арина"),
    Visitor(name: "Осипова Ева"),
    Visitor(name: "Князев Фёдор"),
    Visitor(name: "Маслова Лейла"),
    Visitor(name: "Малышев Мирослав"),
    Visitor(name: "Морозов Данила"),
    Visitor(name: "Серебрякова Анастасия"),
    Visitor(name: "Федоров Александр"),
    Visitor(name: "Василий Пупкин"),
    Visitor(name: "Масленникова Ева"),
    Visitor(name: "Шаповалов Иван"),
    Visitor(name: "Мартынова Мария"),
    Visitor(name: "Иванова Элина"),
    Visitor(name: "Романова Анна"),
    Visitor(name: "Николаев Руслан"),
    Visitor(name: "Винокурова Мария"),
    Visitor(name: "Кириллов Никита"),
    Visitor(name: "Белоусов Фёдор"),
    Visitor(name: "Суворова Арина"),
    Visitor(name: "Осипова Ева"),
    Visitor(name: "Князев Фёдор"),
    Visitor(name: "Маслова Лейла"),
    Visitor(name: "Малышев Мирослав"),
    Visitor(name: "Морозов Данила"),
    Visitor(name: "Серебрякова Анастасия"),
    Visitor(name: "Федоров Александр"),
    Visitor(name: "Василий Пупкин"),
    Visitor(name: "Масленникова Ева"),
    Visitor(name: "Шаповалов Иван"),
    Visitor(name: "Мартынова Мария"),
    Visitor(name: "Иванова Элина"),
    Visitor(name: "Романова Анна"),
    Visitor(name: "Николаев Руслан"),
    Visitor(name: "Винокурова Мария"),
    Visitor(name: "Кириллов Никита"),
    Visitor(name: "Белоусов Фёдор"),
    Visitor(name: "Суворова Арина"),
    Visitor(name: "Осипова Ева"),
    Visitor(name: "Князев Фёдор"),
    Visitor(name: "Маслова Лейла"),
    Visitor(name: "Малышев Мирослав"),
    Visitor(name: "Морозов Данила"),
    Visitor(name: "Серебрякова Анастасия"),
    Visitor(name: "Федоров Александр"),
  ];
}
